networks: (( merge ))

meta:
  environment: ~

  release:
    name: binary-network-test

jobs:
- name: server
  release: (( meta.release.name ))
  template: server
  instances: 0
  resource_pool: small
  networks:
  - name: binary1
    static_ips: ~

- name: client
  release: (( meta.release.name ))
  template: client
  instances: 0
  resource_pool: small
  networks:
  - name: binary1
    static_ips: ~


properties:
  server_address: (( jobs.server.networks.binary1.static_ips.[0] ))
  server_port: 8080
  connection_timeout_in_seconds: 2
  connection_retry_in_seconds: 1
